[project]
name = "practica-04-pizarro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Guillermo Pizarro", email = "gpizarro@espol.edu.ec" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
practica-04-pizarro = "practica_04_pizarro:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
